spring.application.name=oms
spring.datasource.url=jdbc:postgresql://localhost:5432/oms
spring.datasource.username=postgres
spring.datasource.password=ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

spring.jpa.hibernate.ddl-auto=update

