spring.application.name=oms
spring.datasource.url=jdbc:postgresql://localhost:5432/oms
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

