#!/usr/bin/env bash
set -euo pipefail

# Stage 3 of the microservices-prep plan (Phase 4, Customer extraction):
# one-time copy of oms_customer.customers (oms-main) into customers
# (customer-service's own database). See
# docs/stage3-data-cutover-runbook-customer.md for the full
# maintenance-window procedure this script is one step of — do not run this
# on its own without following that runbook, in particular the step
# confirming app.customer.writes-frozen=true has taken effect on EVERY
# running oms-main instance before this script starts.
#
# Requires: psql on PATH, network access to both databases from wherever
# this runs, and a role on each side with SELECT (source) / INSERT (target)
# on the customers table.
#
# NOT idempotent by design — see the pre-flight check below. Re-running
# this against a target that already has rows is refused rather than
# silently double-inserting. Mirrors scripts/stage3-copy-products.sh exactly
# — see that script for the reasoning behind each check.

SOURCE_DSN="${SOURCE_DSN:?Set SOURCE_DSN, e.g. postgresql://user:pass@oms-db-host:5432/oms}"
TARGET_DSN="${TARGET_DSN:?Set TARGET_DSN, e.g. postgresql://user:pass@customer-db-host:5432/customer_service}"

# Column list is explicit and shared between the SELECT and the \copy target
# column list — physical column ORDER differs between the two schemas
# (oms-main's version was added later via ALTER TABLE — V10 — so it's not
# adjacent to status the way customer-service's fresh V1 migration has it),
# but that doesn't matter as long as both sides name the same columns
# explicitly, which this does.
COLUMNS="id, first_name, last_name, email, phone, street, city, state, postal_code, country, status, version, created_at, updated_at"

# Row-level checksum: casting the whole row to text and hashing it avoids
# the false-collision risk of naively concatenating column values with no
# delimiter. Postgres's row-to-text cast handles NULLs and types
# consistently on both sides, since both databases have identical column
# types for every column in $COLUMNS.
checksum_query() {
  local table="$1"
  echo "SELECT md5(string_agg(md5((id, first_name, last_name, email, phone, street, city, state, postal_code, country, status, version, created_at, updated_at)::text), '' ORDER BY id)) FROM ${table};"
}

echo "== Stage 3 data cutover: oms_customer.customers -> customer-service's customers =="
echo

# --- Pre-flight: refuse to run against a non-empty target -----------------
target_count=$(psql "$TARGET_DSN" -tAc "SELECT COUNT(*) FROM customers;")
if [ "$target_count" -ne 0 ]; then
  echo "ABORT: target 'customers' table is not empty ($target_count rows)." >&2
  echo "This script is not idempotent — re-running it against a non-empty" >&2
  echo "target would duplicate every row. If this is a genuine retry after" >&2
  echo "a failed attempt, TRUNCATE customer-service's customers table first" >&2
  echo "(and RESTART IDENTITY to reset the sequence) — see the runbook's" >&2
  echo "rollback section before doing that." >&2
  exit 1
fi

# --- Snapshot the source for later verification ----------------------------
source_count=$(psql "$SOURCE_DSN" -tAc "SELECT COUNT(*) FROM oms_customer.customers;")
source_max_id=$(psql "$SOURCE_DSN" -tAc "SELECT COALESCE(MAX(id), 0) FROM oms_customer.customers;")
source_checksum=$(psql "$SOURCE_DSN" -tAc "$(checksum_query oms_customer.customers)")

echo "Source: $source_count rows, max id $source_max_id"
echo "Source checksum: $source_checksum"
echo

if [ "$source_count" -eq 0 ]; then
  echo "ABORT: source table is empty — refusing to run. An empty source" >&2
  echo "almost certainly means the wrong SOURCE_DSN was given, or the" >&2
  echo "customers table hasn't been migrated to oms_customer yet (see V20)." >&2
  exit 1
fi

# --- Copy --------------------------------------------------------------------
echo "Copying $source_count rows..."
psql "$SOURCE_DSN" -c "\copy (SELECT $COLUMNS FROM oms_customer.customers ORDER BY id) TO STDOUT" \
  | psql "$TARGET_DSN" -c "\copy customers ($COLUMNS) FROM STDIN"

# --- Advance the target's identity sequence ---------------------------------
# customers.id is GENERATED BY DEFAULT AS IDENTITY on both sides, which is
# exactly what allows explicit ids in the \copy above — but the target's
# sequence has no idea those ids were just used. Without this, the next
# INSERT with no explicit id would try id 1 again and hit the primary key.
psql "$TARGET_DSN" -c "SELECT setval(pg_get_serial_sequence('customers', 'id'), $source_max_id);" > /dev/null
echo "Target identity sequence advanced to $source_max_id."
echo

# --- Verify ------------------------------------------------------------------
target_count=$(psql "$TARGET_DSN" -tAc "SELECT COUNT(*) FROM customers;")
target_max_id=$(psql "$TARGET_DSN" -tAc "SELECT COALESCE(MAX(id), 0) FROM customers;")
target_checksum=$(psql "$TARGET_DSN" -tAc "$(checksum_query customers)")

echo "Target: $target_count rows, max id $target_max_id"
echo "Target checksum: $target_checksum"
echo

if [ "$target_count" != "$source_count" ] || [ "$target_checksum" != "$source_checksum" ]; then
  echo "VERIFICATION FAILED — target does not match source." >&2
  echo "  row count:  source=$source_count target=$target_count" >&2
  echo "  checksum:   source=$source_checksum target=$target_checksum" >&2
  echo "DO NOT proceed to unfreezing writes or Stage 4 cutover." >&2
  echo "See the runbook's rollback section." >&2
  exit 1
fi

echo "OK — $target_count rows copied and verified (checksum match, sequence advanced)."
echo "Next: the runbook's post-copy verification queries, then Stage 4 (call-site cutover)."
