-- One row per (order_id, product_id) that inventory has been reserved for, in
-- response to an OrderCreated event. Serves two purposes:
--   1. Idempotency: the unique constraint lets the Kafka consumer detect and
--      skip a line item it has already reserved stock for, so redelivery of
--      the same OrderCreated event (at-least-once) can never double-decrement
--      inventory.
--   2. Audit trail: records exactly how much was reserved per order/product,
--      which Phase 4's compensating "release stock on cancel" flow will need.
CREATE TABLE inventory_reservations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT       NOT NULL,
    product_id  BIGINT       NOT NULL,
    event_id    UUID         NOT NULL,
    quantity    INTEGER      NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_inventory_reservations_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_inventory_reservations_order_product UNIQUE (order_id, product_id)
);

CREATE INDEX idx_inventory_reservations_order_id ON inventory_reservations (order_id);
