CREATE TABLE inventory (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT NOT NULL,
    location           VARCHAR(100) NOT NULL,
    quantity_available INTEGER NOT NULL,
    quantity_reserved  INTEGER NOT NULL,
    reorder_level      INTEGER NOT NULL,
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_inventory_product_location UNIQUE (product_id, location)
);

CREATE INDEX idx_inventory_product_id ON inventory (product_id);
CREATE INDEX idx_inventory_location ON inventory (location);
