CREATE TABLE payments (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT NOT NULL,
    amount                 NUMERIC(10,2) NOT NULL,
    method                 VARCHAR(20) NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    transaction_reference  VARCHAR(100),
    created_at             TIMESTAMP(6) NOT NULL,
    updated_at             TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_payments_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_payments_method CHECK (method IN ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CASH_ON_DELIVERY'))
);

CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_payments_status ON payments (status);
