CREATE TABLE shipments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL,
    carrier         VARCHAR(20) NOT NULL,
    tracking_number VARCHAR(100),
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    shipped_at      TIMESTAMP(6),
    delivered_at    TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_shipments_status CHECK (status IN ('PENDING', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED')),
    CONSTRAINT ck_shipments_carrier CHECK (carrier IN ('UPS', 'FEDEX', 'USPS', 'DHL', 'OTHER'))
);

CREATE INDEX idx_shipments_order_id ON shipments (order_id);
CREATE INDEX idx_shipments_status ON shipments (status);
